const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
    GET_PARTICULAR_PROJECTS: 'GET_PARTICULAR_PROJECTS',
    GET_ALL_DETAILS: 'GET_ALL_DETAILS'
}

export default ACTIONS;